### ISSUE TITLE
Can't connect through UNIX socket

### ISSUE THREAD

**Issue by DenerKup** [yihuang/credis#6]
Hello!

I am creating connection like: `c = credis.Connection(path='/path/to/redis.sock', db=0)`. But after I get error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "credis/base.pyx", line 338, in credis.base.Connection.execute (credis/base.c:6856)
  File "credis/base.pyx", line 204, in credis.base.Connection.send_command (credis/base.c:4286)
  File "credis/base.pyx", line 189, in credis.base.Connection.send_packed_command (credis/base.c:3779)
  File "credis/base.pyx", line 128, in credis.base.Connection.connect (credis/base.c:2476)
credis.base.ConnectionError: Error connecting to (localhost:6379). (111, 'Connection refused').
```

As I can see from [here in code](https://github.com/yihuang/credis/blob/master/credis/base.pyx#L142), connection should go to the socket and I should get an error about socket.

If am passing None to host and port I get error from python's socket lib:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "credis/base.pyx", line 338, in credis.base.Connection.execute (credis/base.c:6856)
  File "credis/base.pyx", line 204, in credis.base.Connection.send_command (credis/base.c:4286)
  File "credis/base.pyx", line 189, in credis.base.Connection.send_packed_command (credis/base.c:3779)
  File "credis/base.pyx", line 126, in credis.base.Connection.connect (credis/base.c:2373)
  File "credis/base.pyx", line 148, in credis.base.Connection._connect (credis/base.c:2944)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

Overall it looks like [this commit](https://github.com/yihuang/credis/commit/d63309803c79d0da350117b6e27345a1b7d586bc) not present in version that downloaded via pip. Is this an actual state of things?

**Comment by yihuang** [comment]
Thanks for reporting, I've forget to upload. Now I've lost my pypi password and I don't get password reset email ;( I will upload current version as soon as I get my password back.
For now, you can use the master version in repository.
